name: automerge_release_to_dev

on:
  pull_request:
    types:
      - closed
    branches:
      - 'release/*' # Trigger on pushes to any branch starting with 'release/'

jobs:
  do-not-automerge:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'do-not-automerge') }}
    name: Prevent Automerging
    runs-on: ubuntu-latest
    steps:
      - name: Check for label
        run: |
          echo "Pull request is labeled as 'do-not-automerge'"
          echo "This workflow fails so that the pull request cannot be merged"
          exit 1
  automerge:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get Commit Information
        run: |
          # Get merge commit SHA (short)
          MERGE_SHA=$(echo ${{ github.event.pull_request.merge_commit_sha }} | cut -c1-7)
          echo "MERGE_SHA=$MERGE_SHA" >> $GITHUB_ENV
          
          # Get PR head SHA (short) - this is the latest commit in the PR
          HEAD_SHA=$(echo ${{ github.event.pull_request.head.sha }} | cut -c1-7)
          echo "HEAD_SHA=$HEAD_SHA" >> $GITHUB_ENV
          
          # Get all commits in the PR
          COMMITS=$(gh pr view ${{ github.event.pull_request.number }} --json commits --jq '.commits[].oid' | cut -c1-7)
          echo "COMMITS=$COMMITS" >> $GITHUB_ENV
          
          # Count commits
          COMMIT_COUNT=$(echo "$COMMITS" | wc -l)
          echo "COMMIT_COUNT=$COMMIT_COUNT" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create Pull Request
        id: create_pr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'Merge release PR $HEAD_SHA into dev'
          title: 'Release PR $HEAD_SHA into dev'
          body: |
            Automated PR to merge release branch into dev.
            
            **Commit Information:**
            - Merge SHA: $MERGE_SHA
            - Head SHA: $HEAD_SHA
            - Total commits: $COMMIT_COUNT
            
            **Commits included:**
            ```
            $COMMITS
            ```
            
            This PR contains all commits from the merged release PR.
          base: main
      - name: Enable Auto-Merge for the PR
        if: steps.create_pr.outputs.pull-request-number # Only run if a PR was created
        run: gh pr merge --merge --auto "1"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
